// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: pb/revision_control.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RevisionControl_CommitFile_FullMethodName = "/pb.RevisionControl/CommitFile"
	RevisionControl_GetFile_FullMethodName    = "/pb.RevisionControl/GetFile"
)

// RevisionControlClient is the client API for RevisionControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RevisionControlClient interface {
	CommitFile(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	GetFile(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type revisionControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRevisionControlClient(cc grpc.ClientConnInterface) RevisionControlClient {
	return &revisionControlClient{cc}
}

func (c *revisionControlClient) CommitFile(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, RevisionControl_CommitFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *revisionControlClient) GetFile(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RevisionControl_GetFile_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RevisionControlServer is the server API for RevisionControl service.
// All implementations must embed UnimplementedRevisionControlServer
// for forward compatibility
type RevisionControlServer interface {
	CommitFile(context.Context, *CommitRequest) (*CommitResponse, error)
	GetFile(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedRevisionControlServer()
}

// UnimplementedRevisionControlServer must be embedded to have forward compatible implementations.
type UnimplementedRevisionControlServer struct {
}

func (UnimplementedRevisionControlServer) CommitFile(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitFile not implemented")
}
func (UnimplementedRevisionControlServer) GetFile(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFile not implemented")
}
func (UnimplementedRevisionControlServer) mustEmbedUnimplementedRevisionControlServer() {}

// UnsafeRevisionControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RevisionControlServer will
// result in compilation errors.
type UnsafeRevisionControlServer interface {
	mustEmbedUnimplementedRevisionControlServer()
}

func RegisterRevisionControlServer(s grpc.ServiceRegistrar, srv RevisionControlServer) {
	s.RegisterService(&RevisionControl_ServiceDesc, srv)
}

func _RevisionControl_CommitFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionControlServer).CommitFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionControl_CommitFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionControlServer).CommitFile(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RevisionControl_GetFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RevisionControlServer).GetFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RevisionControl_GetFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RevisionControlServer).GetFile(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RevisionControl_ServiceDesc is the grpc.ServiceDesc for RevisionControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RevisionControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.RevisionControl",
	HandlerType: (*RevisionControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitFile",
			Handler:    _RevisionControl_CommitFile_Handler,
		},
		{
			MethodName: "GetFile",
			Handler:    _RevisionControl_GetFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/revision_control.proto",
}
